### ISSUE TITLE
可以导出，但是 imdb 打分速度慢，约为每分钟 1 部

### ISSUE THREAD

**Issue by zizhengwu** [fisheepx/douban-to-imdb#13]
首先感谢这么实用的脚本，完全可用。

唯一缺点是速度比较慢，在 imdb 上打分，约为每分钟一部。这样如果有有人看了比较多，比如超过 1000 部，电影，估计得打分一整天。

不算真正的 issue，只是作为讨论。

**Comment by f-is-h** [comment]
这个是由于懒得解析imdb的API还有登录cookie，所以偷懒用了UI式的操作😂 虽然我也马上就到1000部了，但写这个脚本时观影还比较少，所以就没多考虑时间的问题。
