### ISSUE TITLE
“无法在IMDB上找到”

### ISSUE THREAD

**Issue by zayn-0101** [fisheepx/douban-to-imdb#3]
导入电影评分到 IMDB时，全都提示“无法在IMDB上找到” 😂

**Comment by bressanon84** [comment]
> 导入电影评分到 IMDB时，全都提示“无法在IMDB上找到” 😂

同样的问题，爬到的movie.csv里没有imdb ID。

**Comment by f-is-h** [comment]
豆瓣和IMDB页面都改版了，导致原来的定位方法失效。
已经对应到最新版页面了，想导入的话要抓紧导，估计没准哪天又改版了😂

先关闭这个Issue，如果有问题再打开
