### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by s0ren99** [fisheepx/douban-to-imdb#8]
经过亿番修改后，不再报语法错误了。
但是始终报错：
`ModuleNotFoundError: No module named 'bs4'`
安装并指定目录安装bs4和beautifulsoup4也不起作用。

自己的PC上不进入虚拟环境但安装了Requirements，运行之后，成功显示
`开始抓取所有观影数据...`
但抓着抓着又报出一个错误：
```
Traceback (most recent call last):
  File "douban_to_csv.py", line 144, in <module>
    export(sys.argv[1])
  File "douban_to_csv.py", line 113, in export
    info.extend(get_info(url))
TypeError: 'NoneType' object is not iterable
```
详情请见此帖:  ["TypeError: 'NoneType' object is not iterable" in a python file](https://stackoverflow.com/questions/71995147/typeerror-nonetype-object-is-not-iterable-in-a-python-file)

请问我需要改python吗，还是说我又漏了或做错了那一步？

**Comment by f-is-h** [comment]
@SingleRottenChips 
pyenv主要是用于生成个虚拟环境，目的是与其它项目隔离开。
如果没有这个需求的话没有使用pyenv的必要。
说明中的斜体部分_如果不使用虚拟环境，请参照 requirements.txt中的内容自行安装依赖包_
打开requirements.txt确保里面的依赖包都已经安装就可以了。

至于你发截图的这个错误我怀疑是你的操作系统不支持中文所导致的，建议用IDE试试（如VScode，Pycharm等）

如最开始所说，
说明中只给出了一种示例的运行方法，这种方法并不是必需的。
无论什么操作系统，无论用什么IDE，
只要保证Python正确安装，相应的浏览器驱动设置正确，
requirements.txt中给出的依赖包安装成功，
就可以正常运行。

**Comment by s0ren99** [comment]
> @SingleRottenChips pyenv主要是用于生成个虚拟环境，目的是与其它项目隔离开。 如果没有这个需求的话没有使用pyenv的必要。 说明中的斜体部分_如果不使用虚拟环境，请参照 requirements.txt中的内容自行安装依赖包_ 打开requirements.txt确保里面的依赖包都已经安装就可以了。
> 
> 至于你发截图的这个错误我怀疑是你的操作系统不支持中文所导致的，建议用IDE试试（如VScode，Pycharm等）
> 
> 如最开始所说， 说明中只给出了一种示例的运行方法，这种方法并不是必需的。 无论什么操作系统，无论用什么IDE， 只要保证Python正确安装，相应的浏览器驱动设置正确， requirements.txt中给出的依赖包安装成功， 就可以正常运行。

感谢回复！我编辑了帖子，具体情况请看[此帖](https://stackoverflow.com/questions/71995147/syntax-errors-in-a-python-file)。谢谢。
