### ISSUE TITLE
查找自己的豆瓣 ID

### ISSUE THREAD

**Issue by Tofualma** [fisheepx/douban-to-imdb#9]
登录自己的豆瓣账号，然后点击右上角的名字，打开[个人主页](https://www.douban.com/mine/)，就在跳转到的URL里：[https://www.douban.com/people/[这里的数字就是你的user_id]/](https://www.douban.com/people/%5B%E8%BF%99%E9%87%8C%E7%9A%84%E6%95%B0%E5%AD%97%E5%B0%B1%E6%98%AF%E4%BD%A0%E7%9A%84user_id%5D/)

每次刷新页面，这里的数字都是会变化的

**Comment by f-is-h** [comment]
正常打开后的URL形式是：https://www.douban.com/people/<font>**xxxxxxxxx**</font>?_i=4655031a-Z9QGJ,4655034a-Z9QGJ
也许后面的数字会变，但**xxxxxxxxx**这个部分的数字不会变化，这个是你的user id.
